version: '3.8'
name: meeting-groups-app

services:
  postgres-db:
    container_name: postgres-db
    image: postgres:16.3
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - meeting-groups-app-network
  
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:24.0.5
    depends_on:
      postgres-db:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - meeting-groups-app-network

volumes:
  postgres_data:

networks:
  meeting-groups-app-network:
    external: true