version: '3.8'

services:
  postgres-db:
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_PASSWORD: "myPassw0rd"

  keycloak:
    ports:
      - "8080:8080"
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: "postgres-db"
      KC_DB_URL_DATABASE: "keycloak"
      KC_DB_USERNAME: "postgres"
      KC_DB_PASSWORD: "myPassw0rd"
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: "myAdminPassw0rd*"
      KC_HEALTH_ENABLED: "true"
    entrypoint: ["/opt/keycloak/bin/kc.sh", "start-dev"]

    